"""phase 2: device uuid + pairing, cameras, clip.camera_id

Revision ID: 8f8b2b7d50e2
Revises: ace2a86bb3b2
Create Date: 2026-08-02 15:53:07.939806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8b2b7d50e2'
down_revision = 'ace2a86bb3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'name', name='uq_camera_device_name'),
    sa.UniqueConstraint('device_id', 'slug', name='uq_camera_device_slug')
    )
    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('local_filename', sa.String(length=255), nullable=True))
        batch_op.alter_column('s3_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('clips_device_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('clips_camera_id_fkey', 'cameras', ['camera_id'], ['id'])
        batch_op.drop_column('device_id')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('pairing_code_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pairing_code_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('device_key_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_devices_uuid'), ['uuid'], unique=True)
        batch_op.create_unique_constraint('uq_device_establishment', ['establishment_id'])
        batch_op.drop_column('camera_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint('uq_device_establishment', type_='unique')
        batch_op.drop_index(batch_op.f('ix_devices_uuid'))
        batch_op.alter_column('device_key_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('pairing_code_expires_at')
        batch_op.drop_column('pairing_code_hash')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('clips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint('clips_camera_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('clips_device_id_fkey'), 'devices', ['device_id'], ['id'])
        batch_op.alter_column('s3_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
        batch_op.drop_column('local_filename')
        batch_op.drop_column('camera_id')

    op.drop_table('cameras')
    # ### end Alembic commands ###
